# Dependencies
markdown:         rdiscount
#highlighter:      pygments
highlighter:      Rouge

#
encoding:         "utf-8"
# Permalinks
permalink:        pretty

gems: [jekyll-paginate]

# Setup
title:            tiger
tagline:          'be happy'
description:      'enjoy life'
url:              http://xinghuwang.github.io

author:
  name:           'wangxinghu'
  url:            https://github.com/xinghuwang

paginate:         5

# duoshuo
comments :
    provider : duoshuo
    duoshuo :
      short_name : wangxinghu
